-- Fair Play Football base public schema.
-- Run this first on a fresh Supabase project before the feature-specific SQL files.
-- This intentionally does not create RLS policies; apply supabase/rls_policies.sql
-- after this file.

create table if not exists public.profiles (
  id uuid not null,
  email text,
  username text,
  age text,
  gender text,
  favourite_position text,
  created_at timestamptz default now(),
  avatar_url text
);

create table if not exists public.games (
  title text not null,
  location text not null,
  time text,
  price bigint,
  spots_left bigint,
  starts_at timestamptz,
  created_at timestamptz default now(),
  id bigint not null,
  max_players integer default 16,
  status text not null default 'active',
  cancelled_at timestamptz,
  cancelled_by uuid,
  cancellation_reason text,
  archived_at timestamptz,
  archived_by uuid
);

comment on column public.games.starts_at is
'Canonical timezone-aware kickoff timestamp for scheduling and reminder logic.';

comment on column public.games.time is
'Legacy display compatibility field during the starts_at transition; do not use for reminder scheduling.';

comment on column public.games.archived_at is
'Canonical archive flag. Archive is separate from active/cancelled lifecycle status and must never delete or rewrite financial/history records.';

comment on column public.games.archived_by is
'Admin user who archived the game when available; archiving must never delete or rewrite financial/history records.';

create table if not exists public.bookings (
  id bigint not null,
  created_at timestamptz not null default now(),
  player_name text,
  game_id bigint,
  user_id uuid default auth.uid()
);

do $$
begin
  if exists (
    select 1
    from pg_attribute
    where attrelid = 'public.games'::regclass
      and attname = 'id'
      and attidentity = ''
  ) then
    alter table public.games
    alter column id add generated by default as identity;
  end if;

  if exists (
    select 1
    from pg_attribute
    where attrelid = 'public.bookings'::regclass
      and attname = 'id'
      and attidentity = ''
  ) then
    alter table public.bookings
    alter column id add generated by default as identity;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_pkey'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
    add constraint profiles_pkey primary key (id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'games_pkey'
      and conrelid = 'public.games'::regclass
  ) then
    alter table public.games
    add constraint games_pkey primary key (id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bookings_pkey'
      and conrelid = 'public.bookings'::regclass
  ) then
    alter table public.bookings
    add constraint bookings_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_id_fkey'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
    add constraint profiles_id_fkey
    foreign key (id) references auth.users(id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bookings_user_id_fkey'
      and conrelid = 'public.bookings'::regclass
  ) then
    alter table public.bookings
    add constraint bookings_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'games_cancelled_by_fkey'
      and conrelid = 'public.games'::regclass
  ) then
    alter table public.games
    add constraint games_cancelled_by_fkey
    foreign key (cancelled_by) references auth.users(id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'games_archived_by_fkey'
      and conrelid = 'public.games'::regclass
  ) then
    alter table public.games
    add constraint games_archived_by_fkey
    foreign key (archived_by) references auth.users(id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'games_status_check'
      and conrelid = 'public.games'::regclass
  ) then
    alter table public.games
    add constraint games_status_check
    check (status in ('active', 'cancelled'));
  end if;
end $$;

create index if not exists games_status_idx
on public.games(status);

create index if not exists games_archived_at_idx
on public.games(archived_at)
where archived_at is not null;

create index if not exists games_active_unarchived_starts_at_idx
on public.games(starts_at)
where status = 'active'
  and archived_at is null;

create index if not exists games_archived_lookup_idx
on public.games(archived_at, id)
where archived_at is not null;

grant all on table public.profiles to anon;
grant all on table public.profiles to authenticated;
grant all on table public.profiles to service_role;

grant all on table public.games to anon;
grant all on table public.games to authenticated;
grant all on table public.games to service_role;

grant all on sequence public.games_id_seq to anon;
grant all on sequence public.games_id_seq to authenticated;
grant all on sequence public.games_id_seq to service_role;

grant select on table public.bookings to anon;
grant select on table public.bookings to authenticated;
grant all on table public.bookings to service_role;

grant all on sequence public.bookings_id_seq to service_role;
